/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*esto es uina prueba*/
package javaapplication2;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author Borja
 */
public class Articulos extends javax.swing.JFrame {
static public ResultSet r;
static public Connection connection;
int var;
    public Articulos() throws SQLException {
       initComponents();
        String url = "jdbc:mysql://localhost:3306/entornodedesarrollo";
        String user = "root";
        String pass = "";
        connection = DriverManager.getConnection(url,user,pass);
        
        Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "select * from articulos ";
        r = s.executeQuery(query);
        r.first();
        COD_ARTICULO.setText(r.getString("cod_articulo"));
        ARTICULO.setText(r.getString("articulo"));
        
        PESO.setText(r.getString("peso"));
        CATEGORIA.setText(r.getString("categoria"));
        PRECIO_VENTA.setText(r.getString("precio_venta"));
        PRECIO_COSTE.setText(r.getString("precio_coste"));
        EXISTENCIAS.setText(r.getString("existencias"));
        connection = DriverManager.getConnection(url, user, pass);
        String query2 = "select * from fabricantes";
        ResultSet r2;
        Statement s2 = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        r2 = s2.executeQuery(query2);
        DefaultComboBoxModel value1 = new DefaultComboBoxModel();
        
        while(r2.next()){
            value1.addElement(r2.getString("NOMBRE"));
        }
        NOMFABRICANTE.setModel(value1);
        NOMFABRICANTE.setSelectedItem(getNOMFABRICANTE(r.getInt("fabricante")));
       CONFIRMAR.setVisible(false);
        CANCELAR.setVisible(false);
            
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<String>();
        SIGUIENTE = new javax.swing.JButton();
        ULTIMA = new javax.swing.JButton();
        NUEVA = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        PRIMERA = new javax.swing.JButton();
        ANTERIOR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PRECIO_COSTE = new javax.swing.JTextField();
        COD_ARTICULO = new javax.swing.JTextField();
        ARTICULO = new javax.swing.JTextField();
        PESO = new javax.swing.JTextField();
        PRECIO_VENTA = new javax.swing.JTextField();
        EXISTENCIAS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CONFIRMAR = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CATEGORIA = new javax.swing.JTextField();
        BORRAR = new javax.swing.JButton();
        NOMFABRICANTE = new javax.swing.JComboBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SIGUIENTE.setText("SIGUIENTE");
        SIGUIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGUIENTEActionPerformed(evt);
            }
        });

        ULTIMA.setText("ULTIMA");
        ULTIMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ULTIMAActionPerformed(evt);
            }
        });

        NUEVA.setText("NUEVA");
        NUEVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVAActionPerformed(evt);
            }
        });

        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        PRIMERA.setText("PRIMERA");
        PRIMERA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRIMERAActionPerformed(evt);
            }
        });

        ANTERIOR.setText("ANTERIOR");
        ANTERIOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTERIORActionPerformed(evt);
            }
        });

        jLabel1.setText("COD_ARTICULO");

        jLabel2.setText("ARTICULO");

        jLabel3.setText("FABRICANTE");

        jLabel4.setText("PESO");

        jLabel5.setText("PRECIO_VENTA");

        jLabel6.setText("PRECIO_COSTE");

        jLabel7.setText("EXISTENCIAS");

        PRECIO_COSTE.setEditable(false);
        PRECIO_COSTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRECIO_COSTEActionPerformed(evt);
            }
        });

        COD_ARTICULO.setEditable(false);
        COD_ARTICULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COD_ARTICULOActionPerformed(evt);
            }
        });

        ARTICULO.setEditable(false);
        ARTICULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARTICULOActionPerformed(evt);
            }
        });

        PESO.setEditable(false);

        PRECIO_VENTA.setEditable(false);
        PRECIO_VENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRECIO_VENTAActionPerformed(evt);
            }
        });

        EXISTENCIAS.setEditable(false);
        EXISTENCIAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXISTENCIASActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Articulos");

        CONFIRMAR.setText("CONFIRMAR");
        CONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRMARActionPerformed(evt);
            }
        });

        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        jLabel9.setText("CATEGORIA");

        CATEGORIA.setEditable(false);
        CATEGORIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CATEGORIAActionPerformed(evt);
            }
        });

        BORRAR.setText("BORRAR");
        BORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRARActionPerformed(evt);
            }
        });

        NOMFABRICANTE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NOMFABRICANTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMFABRICANTEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(CONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CATEGORIA, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(EXISTENCIAS)
                    .addComponent(PRECIO_VENTA)
                    .addComponent(PESO)
                    .addComponent(COD_ARTICULO)
                    .addComponent(PRECIO_COSTE)
                    .addComponent(ARTICULO)
                    .addComponent(NOMFABRICANTE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(BORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PRIMERA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ULTIMA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SIGUIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ANTERIOR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NUEVA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(COD_ARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addComponent(PRECIO_COSTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(ARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NOMFABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PRECIO_VENTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EXISTENCIAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRIMERA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANTERIOR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUEVA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SIGUIENTE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ULTIMA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(BORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SIGUIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGUIENTEActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if(r.next()){;
            PRECIO_COSTE.setText(r.getString("PRECIO_COSTE"));
            COD_ARTICULO.setText(r.getString("COD_ARTICULO"));
            ARTICULO.setText(r.getString("ARTICULO"));
        NOMFABRICANTE.setSelectedItem(getNOMFABRICANTE(r.getInt("fabricante")));
            PESO.setText(r.getString("PESO"));
            PRECIO_VENTA.setText(r.getString("PRECIO_VENTA"));
            EXISTENCIAS.setText(r.getString("EXISTENCIAS"));
            CATEGORIA.setText(r.getString("CATEGORIA"));
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SIGUIENTEActionPerformed

    private void ULTIMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ULTIMAActionPerformed
        try {
            // TODO add your handling code here:
            r.last();
            PRECIO_COSTE.setText(r.getString("PRECIO_COSTE"));
            COD_ARTICULO.setText(r.getString("COD_ARTICULO"));
            ARTICULO.setText(r.getString("ARTICULO"));
            PESO.setText(r.getString("PESO"));
            PRECIO_VENTA.setText(r.getString("PRECIO_VENTA"));
            EXISTENCIAS.setText(r.getString("EXISTENCIAS"));
        NOMFABRICANTE.setSelectedItem(getNOMFABRICANTE(r.getInt("fabricante")));
            CATEGORIA.setText(r.getString("CATEGORIA"));
            
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ULTIMAActionPerformed

    private void PRIMERAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRIMERAActionPerformed
        try {
            // TODO add your handling code here:
            r.first();
                    NOMFABRICANTE.setSelectedItem(getNOMFABRICANTE(r.getInt("fabricante")));
            PRECIO_COSTE.setText(r.getString("PRECIO_COSTE"));
            COD_ARTICULO.setText(r.getString("COD_ARTICULO"));
            ARTICULO.setText(r.getString("ARTICULO"));
            PESO.setText(r.getString("PESO"));
            PRECIO_VENTA.setText(r.getString("PRECIO_VENTA"));
            EXISTENCIAS.setText(r.getString("EXISTENCIAS"));
            CATEGORIA.setText(r.getString("CATEGORIA"));
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PRIMERAActionPerformed

    private void ANTERIORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTERIORActionPerformed
        // TODO add your handling code here:
        try {
            if(r.previous()){
                        NOMFABRICANTE.setSelectedItem(getNOMFABRICANTE(r.getInt("fabricante")));
               PRECIO_COSTE.setText(r.getString("PRECIO_COSTE"));
            COD_ARTICULO.setText(r.getString("COD_ARTICULO"));
            ARTICULO.setText(r.getString("ARTICULO"));
            PESO.setText(r.getString("PESO"));
            PRECIO_VENTA.setText(r.getString("PRECIO_VENTA"));
            EXISTENCIAS.setText(r.getString("EXISTENCIAS"));
            CATEGORIA.setText(r.getString("CATEGORIA"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ANTERIORActionPerformed

    private void PRECIO_COSTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRECIO_COSTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRECIO_COSTEActionPerformed

    private void ARTICULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARTICULOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ARTICULOActionPerformed

    private void PRECIO_VENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRECIO_VENTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRECIO_VENTAActionPerformed

    private void NUEVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVAActionPerformed
        // TODO add your handling code here:
        var=1;
            COD_ARTICULO.setEditable(true);
            PRECIO_COSTE.setEditable(true);
            ARTICULO.setEditable(true);
            PESO.setEditable(true);
            PRECIO_VENTA.setEditable(true);
            EXISTENCIAS.setEditable(true);
            CATEGORIA.setEditable(true);
            COD_ARTICULO.setText("");
            PRECIO_COSTE.setText("");
            ARTICULO.setText("");
            PESO.setText("");
            PRECIO_VENTA.setText("");
            EXISTENCIAS.setText("");
            CATEGORIA.setText("");
            
            CONFIRMAR.setVisible(true);
            CANCELAR.setVisible(true);
            PRIMERA.setEnabled(false);
            ULTIMA.setEnabled(false);
            ANTERIOR.setEnabled(false);
            SIGUIENTE.setEnabled(false);
            MODIFICAR.setEnabled(false);
             BORRAR.setEnabled(false);
             NUEVA.setEnabled(false);
            // NOMFABRICANTE.setSelectedItem(getNOMFABRICANTE(r.getInt("FABRICANTE")));
    }//GEN-LAST:event_NUEVAActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
     CONFIRMAR.setVisible(true);
            CANCELAR.setVisible(true);
            PRIMERA.setEnabled(false);
            ULTIMA.setEnabled(false);
            ANTERIOR.setEnabled(false);
            SIGUIENTE.setEnabled(false);
            MODIFICAR.setEnabled(false);
             BORRAR.setEnabled(false);
             NUEVA.setEnabled(false);
            PRECIO_COSTE.setEditable(true);
            ARTICULO.setEditable(true);
            PESO.setEditable(true);
            PRECIO_VENTA.setEditable(true);
            EXISTENCIAS.setEditable(true);
            CATEGORIA.setEditable(true);             var=2;
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void EXISTENCIASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXISTENCIASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXISTENCIASActionPerformed

    private void COD_ARTICULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COD_ARTICULOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COD_ARTICULOActionPerformed

    private void CONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRMARActionPerformed
        // TODO add your handling code here:
        if (var==1){
           
        try { COD_ARTICULO.setEditable(false);
        PRECIO_COSTE.setEditable(false);
            ARTICULO.setEditable(false);
            PESO.setEditable(false);
            PRECIO_VENTA.setEditable(false);
            EXISTENCIAS.setEditable(false);
            CATEGORIA.setEditable(false);
            String vCOD_ARTICULO,vPRECIO_COSTE,vARTICULO,vFabri,vPESO, vPRECIO_VENTA,vEXISTENCIAS,vCATEGORIA,vnombre;
    vCOD_ARTICULO=COD_ARTICULO.getText();
    vPRECIO_COSTE=PRECIO_COSTE.getText();
    vARTICULO=ARTICULO.getText();
    vPESO=PESO.getText();
    vPRECIO_VENTA=PRECIO_VENTA.getText();
    vEXISTENCIAS=EXISTENCIAS.getText();
    vCATEGORIA=CATEGORIA.getText();
    vFabri=(String)NOMFABRICANTE.getSelectedItem();
int vFABRICANTE=getCodFabricante(vFabri);
    String url="jdbc:mysql://localhost:3306/entornodedesarrollo";
    String user="root";
    String pass="";
            connection = DriverManager.getConnection(url,user,pass);
    Statement s=connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
    String query = "insert articulos values ('" + vCOD_ARTICULO + "','" + vARTICULO + "','" + vFABRICANTE + "','" + vPESO + "','" + vCATEGORIA + "','" + vPRECIO_VENTA + "','" + vPRECIO_COSTE + "','" + vEXISTENCIAS + "')";
    int resultado=s.executeUpdate(query);
String query2= "select * from articulos";
            r=s.executeQuery(query2);
    r.first();
            CONFIRMAR.setVisible(false);
            CANCELAR.setVisible(false);
            PRIMERA.setEnabled(true);
            ULTIMA.setEnabled(true);
            ANTERIOR.setEnabled(true);
            SIGUIENTE.setEnabled(true);
            MODIFICAR.setEnabled(true);
             BORRAR.setEnabled(true);
             NUEVA.setEnabled(true);
}  catch (SQLException ex) {
    Logger.getLogger(Frabricantes.class.getName()).log(Level.SEVERE, null, ex);
} }
        if (var==2){
         try {
    String vCOD_ARTICULO,vPRECIO_COSTE,vARTICULO,vFabri,vPESO, vPRECIO_VENTA,vEXISTENCIAS,vCATEGORIA;
    //int vFABRICANTE = (String) NOMFABRICANTE.getSelectItem();
    vCOD_ARTICULO=COD_ARTICULO.getText();
    vPRECIO_COSTE=PRECIO_COSTE.getText();
    vARTICULO=ARTICULO.getText();
    vFabri=(String)NOMFABRICANTE.getSelectedItem();
int vFABRICANTE=getCodFabricante(vFabri);
    vPESO=PESO.getText();
    vPRECIO_VENTA=PRECIO_VENTA.getText();
    vEXISTENCIAS=EXISTENCIAS.getText();
    vCATEGORIA=CATEGORIA.getText();
    String url="jdbc:mysql://localhost:3306/entornodedesarrollo";
    String user="root";
    String pass="";
    connection = DriverManager.getConnection(url,user,pass);
    Statement s=connection.createStatement();
    String query = "update articulos set PRECIO_COSTE='" + vPRECIO_COSTE + "', ARTICULO='" + vARTICULO + "', FABRICANTE='" + vFABRICANTE + "', PESO='" + vPESO + "', PRECIO_VENTA='" + vPRECIO_VENTA + "', EXISTENCIAS='" + vEXISTENCIAS + "', CATEGORIA='" + vCATEGORIA +"' WHERE COD_ARTICULO='" + vCOD_ARTICULO +"'";
    int resultado=s.executeUpdate(query);
    String query2= "select * from articulos";
            r=s.executeQuery(query2);
    r.first();
    PRECIO_COSTE.setEditable(false);
            ARTICULO.setEditable(false);
            PESO.setEditable(false);
            PRECIO_VENTA.setEditable(false);
            EXISTENCIAS.setEditable(false);
            CATEGORIA.setEditable(false);
    CONFIRMAR.setVisible(false);
            CANCELAR.setVisible(false);
            PRIMERA.setEnabled(true);
            ULTIMA.setEnabled(true);
            ANTERIOR.setEnabled(true);
            SIGUIENTE.setEnabled(true);
            MODIFICAR.setEnabled(true);
             BORRAR.setEnabled(true);
             NUEVA.setEnabled(true);
}  catch (SQLException ex) {
    Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
} }
        if (var==3){
         try { COD_ARTICULO.setEditable(false);
            String vCOD_ARTICULO;
            vCOD_ARTICULO=COD_ARTICULO.getText();
            String url="jdbc:mysql://localhost:3306/entornodedesarrollo";
            String user="root";
            String pass="";        
            Connection connection = DriverManager.getConnection(url,user,pass);
            Statement s=connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "DELETE FROM articulos WHERE COD_ARTICULO='"+vCOD_ARTICULO+"'";
            int resultado=s.executeUpdate(query);
            String query2= "select * from articulos";
            r=s.executeQuery(query2);
            //r.refreshRow();
            r.first();
            CONFIRMAR.setVisible(false);
            CANCELAR.setVisible(false);
            PRIMERA.setEnabled(true);
            ULTIMA.setEnabled(true);
            ANTERIOR.setEnabled(true);
            SIGUIENTE.setEnabled(true);
            MODIFICAR.setEnabled(true);
            BORRAR.setEnabled(true);
            NUEVA.setEnabled(true);
            }  catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }}
    }//GEN-LAST:event_CONFIRMARActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
         try {
            // TODO add your handling code here:
            r.first();
            COD_ARTICULO.setEditable(false);
            PRECIO_COSTE.setEditable(false);
            ARTICULO.setEditable(false);
            PESO.setEditable(false);
            PRECIO_VENTA.setEditable(false);
            EXISTENCIAS.setEditable(false);
            CATEGORIA.setEditable(false);
           PRECIO_COSTE.setText(r.getString("PRECIO_COSTE"));
            COD_ARTICULO.setText(r.getString("COD_ARTICULO"));
            ARTICULO.setText(r.getString("ARTICULO"));
            PESO.setText(r.getString("PESO"));
            PRECIO_VENTA.setText(r.getString("PRECIO_VENTA"));
            EXISTENCIAS.setText(r.getString("EXISTENCIAS"));
            CATEGORIA.setText(r.getString("CATEGORIA"));
            CONFIRMAR.setVisible(false);
            CANCELAR.setVisible(false);
            PRIMERA.setEnabled(true);
            ULTIMA.setEnabled(true);
            ANTERIOR.setEnabled(true);
            SIGUIENTE.setEnabled(true);
            MODIFICAR.setEnabled(true);
             BORRAR.setEnabled(true);
             NUEVA.setEnabled(true);
             
            } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CANCELARActionPerformed

    private void CATEGORIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CATEGORIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CATEGORIAActionPerformed

    private void BORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRARActionPerformed
            CONFIRMAR.setVisible(true);
            CANCELAR.setVisible(true);
            PRIMERA.setEnabled(false);
            ULTIMA.setEnabled(false);
            ANTERIOR.setEnabled(false);
            SIGUIENTE.setEnabled(false);
            MODIFICAR.setEnabled(false);
             BORRAR.setEnabled(false);
             NUEVA.setEnabled(false);
             var=3;
    }//GEN-LAST:event_BORRARActionPerformed

    private void NOMFABRICANTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMFABRICANTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOMFABRICANTEActionPerformed

    
    //metodos
    public static String getNOMFABRICANTE(int codigo){
         String nombre="";
        
        try{
        Statement s = connection.createStatement();
            String query2 = "select nombre "
                + "from fabricantes "
                + "where cod_fabricante="+codigo;
        ResultSet r2;
            r2 = s.executeQuery(query2);
            r2.first();
            nombre = r2.getString("NOMBRE");
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
        return nombre;
    }
    
    public static int getCodFabricante(String nombre){
      int codigo=0;
        
        try{
            Statement s = connection.createStatement();
            String query2 = "select cod_fabricante from fabricantes where nombre='"+nombre+"'";
            ResultSet r2;
            r2 = s.executeQuery(query2);
            r2.first();
            codigo = r2.getInt("COD_FABRICANTE");
        } catch (SQLException ex){
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
        return codigo;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Articulos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANTERIOR;
    private javax.swing.JTextField ARTICULO;
    private javax.swing.JButton BORRAR;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JTextField CATEGORIA;
    private javax.swing.JTextField COD_ARTICULO;
    private javax.swing.JButton CONFIRMAR;
    private javax.swing.JTextField EXISTENCIAS;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JComboBox NOMFABRICANTE;
    private javax.swing.JButton NUEVA;
    private javax.swing.JTextField PESO;
    private javax.swing.JTextField PRECIO_COSTE;
    private javax.swing.JTextField PRECIO_VENTA;
    private javax.swing.JButton PRIMERA;
    private javax.swing.JButton SIGUIENTE;
    private javax.swing.JButton ULTIMA;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
