/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;
/*esto se supone que es una rama*/
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Borja
 */
public class Frabricantes extends javax.swing.JFrame {
static public ResultSet r;
int var;
    public Frabricantes() throws SQLException {
        initComponents();
        String url = "jdbc:mysql://localhost:3306/entornodedesarrollo";
        String user = "root";
        String pass = "";
        Connection connection = DriverManager.getConnection(url, user,pass);
        
        Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "select * from fabricantes";
        r = s.executeQuery(query);
        r.first();
        COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
        NOMBRE.setText(r.getString("NOMBRE"));
        PAIS.setText(r.getString("PAIS"));
        CONFIRMAR.setVisible(false);
        CC.setVisible(false);
        
//         public Frabricantes() {
   //     initComponents();
    }
    /**
     * Creates new form Frabricantes
     */
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        COD_FABRICANTE = new javax.swing.JTextField();
        NOMBRE = new javax.swing.JTextField();
        PAIS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SIGUIENTE = new javax.swing.JButton();
        ULTIMA = new javax.swing.JButton();
        NUEVA = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        PRIMERA = new javax.swing.JButton();
        ANTERIOR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CONFIRMAR = new javax.swing.JButton();
        BORRAR = new javax.swing.JButton();
        CC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("NOMBRE");

        jLabel3.setText("PAIS");

        COD_FABRICANTE.setEditable(false);
        COD_FABRICANTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COD_FABRICANTEActionPerformed(evt);
            }
        });

        NOMBRE.setEditable(false);

        PAIS.setEditable(false);

        jLabel1.setText("COD_FABRICANTE");

        SIGUIENTE.setText("SIGUIENTE");
        SIGUIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGUIENTEActionPerformed(evt);
            }
        });

        ULTIMA.setText("ULTIMA");
        ULTIMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ULTIMAActionPerformed(evt);
            }
        });

        NUEVA.setText("NUEVA");
        NUEVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVAActionPerformed(evt);
            }
        });

        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        PRIMERA.setText("PRIMERA");
        PRIMERA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRIMERAActionPerformed(evt);
            }
        });

        ANTERIOR.setText("ANTERIOR");
        ANTERIOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTERIORActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Fabricantes");

        CONFIRMAR.setText("CONFIRMAR");
        CONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRMARActionPerformed(evt);
            }
        });

        BORRAR.setText("BORRAR");
        BORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRARActionPerformed(evt);
            }
        });

        CC.setText("CANCELAR");
        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addComponent(CONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(COD_FABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PRIMERA, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(ULTIMA, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(NUEVA, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ANTERIOR, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(SIGUIENTE, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MODIFICAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PAIS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(BORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(COD_FABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PAIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ANTERIOR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PRIMERA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SIGUIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ULTIMA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUEVA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BORRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COD_FABRICANTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COD_FABRICANTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COD_FABRICANTEActionPerformed

    private void SIGUIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGUIENTEActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if(r.next()){;
                COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
                NOMBRE.setText(r.getString("NOMBRE"));
                PAIS.setText(r.getString("PAIS"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SIGUIENTEActionPerformed

    private void ULTIMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ULTIMAActionPerformed
        try {
            // TODO add your handling code here:
            r.last();
                COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
                NOMBRE.setText(r.getString("NOMBRE"));
                PAIS.setText(r.getString("PAIS"));
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ULTIMAActionPerformed

    private void PRIMERAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRIMERAActionPerformed
        try {
            // TODO add your handling code here:
            r.first();
                COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
                NOMBRE.setText(r.getString("NOMBRE"));
                PAIS.setText(r.getString("PAIS"));
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PRIMERAActionPerformed

    private void ANTERIORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTERIORActionPerformed
        // TODO add your handling code here:
        try {
            if(r.previous()){
                COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
                NOMBRE.setText(r.getString("NOMBRE"));
                PAIS.setText(r.getString("PAIS"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ANTERIORActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed

    
    CONFIRMAR.setVisible(true);
    NOMBRE.setEditable(true);
        PAIS.setEditable(true);
            CC.setVisible(true);
            PRIMERA.setEnabled(false);
            ULTIMA.setEnabled(false);
            ANTERIOR.setEnabled(false);
            SIGUIENTE.setEnabled(false);
            MODIFICAR.setEnabled(false);
            BORRAR.setEnabled(false);
            NUEVA.setEnabled(false);
     var=2;
    // TODO add your handling code here:
    } 

//}    }//GEN-LAST:event_MODIFICARActionPerformed

    private void NUEVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVAActionPerformed
        // TODO add your handling code here:
        
        COD_FABRICANTE.setEditable(true);
        NOMBRE.setEditable(true);
        PAIS.setEditable(true);
            COD_FABRICANTE.setText("");
            NOMBRE.setText("");
            PAIS.setText("");
            CONFIRMAR.setVisible(true);
            CC.setVisible(true);
            PRIMERA.setEnabled(false);
            ULTIMA.setEnabled(false);
            ANTERIOR.setEnabled(false);
            SIGUIENTE.setEnabled(false);
            MODIFICAR.setEnabled(false); 
            BORRAR.setEnabled(false);
            NUEVA.setEnabled(false);
            var=1;
    }//GEN-LAST:event_NUEVAActionPerformed

    private void CONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRMARActionPerformed
        // TODO add your handling code here:
        
          if (var==1){
        try { COD_FABRICANTE.setEditable(false);
        NOMBRE.setEditable(false);
        PAIS.setEditable(false);
            String vCodigo, vNombre, vPais;
            vCodigo=COD_FABRICANTE.getText();
            vNombre=NOMBRE.getText();
            vPais=PAIS.getText();
            String url="jdbc:mysql://localhost:3306/entornodedesarrollo";
              String user="root";
            String pass="";        Connection connection = DriverManager.getConnection(url,user,pass);
    Statement s=connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
    String query = "insert Fabricantes values('" + vCodigo + "','" + vNombre + "','" + vPais +"')";
    int resultado=s.executeUpdate(query);
String query2= "select * from fabricantes";
            r=s.executeQuery(query2);
    r.first();
            CONFIRMAR.setVisible(false);
            CC.setVisible(false);
            PRIMERA.setEnabled(true);
            ULTIMA.setEnabled(true);
            ANTERIOR.setEnabled(true);
            SIGUIENTE.setEnabled(true);
            MODIFICAR.setEnabled(true);
             BORRAR.setEnabled(true);
             NUEVA.setEnabled(true);
}  catch (SQLException ex) {
    Logger.getLogger(Frabricantes.class.getName()).log(Level.SEVERE, null, ex);
} }
        if (var==2){
         try {
            COD_FABRICANTE.setEditable(false);
            String vCOD_FABRICANTE, vNombre, vPais;
            vCOD_FABRICANTE=COD_FABRICANTE.getText();
            vNombre=NOMBRE.getText();
            vPais=PAIS.getText();
    String url="jdbc:mysql://localhost:3306/entornodedesarrollo";
    String user="root";
    String pass="";
    Connection connection = DriverManager.getConnection(url,user,pass);
    Statement s=connection.createStatement();
    String query = "update Fabricantes set NOMBRE='"+vNombre+"',PAIS='" + vPais + "' WHERE COD_FABRICANTE='" + vCOD_FABRICANTE +"'";
    int resultado=s.executeUpdate(query);
            String query2= "select * from fabricantes";
            r=s.executeQuery(query2);
    r.first();
        NOMBRE.setEditable(false);
        PAIS.setEditable(false);
        CONFIRMAR.setVisible(false);
            CC.setVisible(false);
            PRIMERA.setEnabled(true);
            ULTIMA.setEnabled(true);
            ANTERIOR.setEnabled(true);
            SIGUIENTE.setEnabled(true);
            MODIFICAR.setEnabled(true);
            BORRAR.setEnabled(true);
            NUEVA.setEnabled(true);


}  catch (SQLException ex) {
    Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
}}
        if (var==3){
         try {
            String vCOD_FABRICANTE,vNombre,vPais;
            vCOD_FABRICANTE=COD_FABRICANTE.getText();
            String url="jdbc:mysql://localhost:3306/entornodedesarrollo";
            String user="root";
            String pass="";        
            Connection connection = DriverManager.getConnection(url,user,pass);
            Statement s=connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "DELETE FROM fabricantes WHERE COD_FABRICANTE='"+vCOD_FABRICANTE+"'";
            int resultado=s.executeUpdate(query);
            String query2= "select * from fabricantes";
            r=s.executeQuery(query2);
            //r.refreshRow();
            r.first();
            CONFIRMAR.setVisible(false);
            CC.setVisible(false);
            PRIMERA.setEnabled(true);
            ULTIMA.setEnabled(true);
            ANTERIOR.setEnabled(true);
            SIGUIENTE.setEnabled(true);
            MODIFICAR.setEnabled(true);
            BORRAR.setEnabled(true);
            NUEVA.setEnabled(true);
            }  catch (SQLException ex) {
            Logger.getLogger(Frabricantes.class.getName()).log(Level.SEVERE, null, ex);
        } }
    }                                         

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {                                         
           try {COD_FABRICANTE.setEditable(false);
            NOMBRE.setEditable(true);
            PAIS.setEditable(true);
            // TODO add your handling code here:
            r.first();
           COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
            NOMBRE.setText(r.getString("NOMBRE"));
            PAIS.setText(r.getString("PAIS"));
            CONFIRMAR.setVisible(false);
            CC.setVisible(false);
            PRIMERA.setEnabled(true);
            ULTIMA.setEnabled(true);
            ANTERIOR.setEnabled(true);
            SIGUIENTE.setEnabled(true);
            MODIFICAR.setEnabled(true);  
            BORRAR.setEnabled(true);
           NUEVA.setEnabled(true);} 
           catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);  }
    }//GEN-LAST:event_CONFIRMARActionPerformed

    private void BORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRARActionPerformed
            CONFIRMAR.setVisible(true);
            CC.setVisible(true);
            PRIMERA.setEnabled(false);
            ULTIMA.setEnabled(false);
            ANTERIOR.setEnabled(false);
            SIGUIENTE.setEnabled(false);
            MODIFICAR.setEnabled(false); 
            BORRAR.setEnabled(false);
            NUEVA.setEnabled(false);
            var=3;
    }//GEN-LAST:event_BORRARActionPerformed

    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        try { COD_FABRICANTE.setEditable(false);
        NOMBRE.setEditable(false);
        PAIS.setEditable(false);
            // TODO add your handling code here:
            r.first();
             COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
             NOMBRE.setText(r.getString("NOMBRE"));
             PAIS.setText(r.getString("PAIS"));
            CONFIRMAR.setVisible(false);
            CC.setVisible(false);
            PRIMERA.setEnabled(true);
            ULTIMA.setEnabled(true);
            ANTERIOR.setEnabled(true);
            SIGUIENTE.setEnabled(true);
            MODIFICAR.setEnabled(true);
             BORRAR.setEnabled(true);
             NUEVA.setEnabled(true);
            } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CCActionPerformed
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frabricantes().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Frabricantes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANTERIOR;
    private javax.swing.JButton BORRAR;
    private javax.swing.JButton CC;
    private javax.swing.JTextField COD_FABRICANTE;
    private javax.swing.JButton CONFIRMAR;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JButton NUEVA;
    private javax.swing.JTextField PAIS;
    private javax.swing.JButton PRIMERA;
    private javax.swing.JButton SIGUIENTE;
    private javax.swing.JButton ULTIMA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void setEnabble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setText(String _) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
